GITHUB_ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/agentswarm/github.env"
AGENTSWARM_ENV_FILE="$HOME/.agentswarm-shell-env"

[ -f "$AGENTSWARM_ENV_FILE" ] && source "$AGENTSWARM_ENV_FILE"
[ -f "$GITHUB_ENV_FILE" ] && source "$GITHUB_ENV_FILE"

PS1='\[\e[32m\]\u@\h\[\e[0m\]:\[\e[34m\]\w\[\e[0m\]\$ '

if [ -x "$HOME/.local/bin/github-askpass" ]; then
  export GIT_ASKPASS="$HOME/.local/bin/github-askpass"
  export GIT_TERMINAL_PROMPT=0
fi
