GITHUB_ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/agentswarm/github.env"

[ -f "$GITHUB_ENV_FILE" ] && source "$GITHUB_ENV_FILE"

PS1='%n@%m:%~$ '

if [ -x "$HOME/.local/bin/github-askpass" ]; then
  export GIT_ASKPASS="$HOME/.local/bin/github-askpass"
  export GIT_TERMINAL_PROMPT=0
fi
